### ISSUE TITLE
checkUserSubscription has wrong requiredAuth value

### ISSUE THREAD

**Issue by cookiekitty** [IBurn36360/Twitch_Interface#10]
This line: $requiredAuth = 'user_subscriptions';

should be: $requiredAuth = 'channel_check_subscription';

**Comment by IBurn36360** [comment]
I need to get back to rewriting this, as much of the API has changed.  I'm honestly surprised most all of this library is still working as well as it is without any real updates.  The next major update should be the ground-up rewrite and composer support will be a core thought.
