### ISSUE TITLE
How to use modules like cURL_get?

### ISSUE THREAD

**Issue by iDentity1337** [IBurn36360/Twitch_Interface#11]
Retarded question here. How can I use these private modules like cURL_get, I'm getting 'Call to private method' when doing it directly:
    <?
    include('twitch/interface/twitch_interface.php');
    $tw = new twitch;
    print_r($tw->curl_get('https://api.twitch.tv/kraken/streams/dreamhackcs'));
    ?>
I've read in documentation something about extending the class but didn't quite understand it.

**Comment by IBurn36360** [comment]
PHP classes and safety is part of Object Oriented Programming (OOP).  http://php.net/manual/en/language.oop5.php is a good place to start in learning mostly the terminology and understanding how to start working with classes.  http://code.tutsplus.com/tutorials/object-oriented-php-for-beginners--net-12762 seems like a pretty good place to start in understanding what to actually do with classes and OOP.

That all said, the cURL set of functions and the iterator (How the interface grabs thousands of rows at a time with a single call) are only designed to be used by people who have a strong knowledge of both Twitch's API and the interface itself.  I recommend against using them, or trying to use them if you do not have a strong understanding of both.

After all of that is said and done, however, there is still hope for getting the information, as there is a set of functions designed to do this exact task for you.  https://github.com/IBurn36360/Twitch_Interface/blob/master/Modules/streams.md (streams) is a module designed to deal with handling stream objects themselves.  I would suggest the following to be able to grab the stream object for a single channel:

```php
<?
include('twitch/interface/twitch_interface.php');
$tw = new twitch;

echo '<pre style="background: #FDF5E9;color: #000000;border: 1px solid #6A6A6A;padding: 9px;max-width: 100%;overflow: auto;max-height: 800px;-webkit-box-shadow: inset 1px 1px 8px 2px rgba(0,0,0,0.3);-khtml-box-shadow: inset 1px 1px 8px 2px rgba(0,0,0,0.3);-moz-box-shadow: inset 1px 1px 8px 2px rgba(0,0,0,0.3);-ms-box-shadow: inset 1px 1px 8px 2px rgba(0,0,0,0.3);-o-box-shadow: inset 1px 1px 8px 2px rgba(0,0,0,0.3);box-shadow: inset 1px 1px 8px 2px rgba(0,0,0,0.3);">';

var_dump($tw->getStreamObject('dreamhackcs'));

echo '<pre>';
?>
```

Most all of the endpoint in Twitch's Kraken API are covered in this manner, so you should only need to interact with the private cURL methods if there are no endpoints covered.

Hope this has helped you out,

\- Anthony Diaz

**Comment by iDentity1337** [comment]
getStreamObject is exactly what I needed. Thank you :+1:
