### ISSUE TITLE
generateToken() is always invalid

### ISSUE THREAD

**Issue by Sydth** [IBurn36360/Twitch_Interface#12]
```
if(isset($_GET['code'])) {
     $user_code = $_GET['code'];
     $testToken = $interface->generateToken($user_code);
     echo json_encode($testToken);
}
```

The code is correct, yet it isn't able to get a valid token, ever.

> 05-21-16||05:25:37 => Generate_Token || Generating auth token
05-21-16||05:25:37 => POST || Starting POST query
05-21-16||05:25:37 => POST || Header row => Accept: application/vnd.twitchtv.v3+json
05-21-16||05:25:37 => POST || Header row => Client-ID: asd (these are correct)
05-21-16||05:25:37 => POST || API Version set to: 3
05-21-16||05:25:37 => POST || No additional options set
05-21-16||05:25:37 => POST || Options set as an array
05-21-16||05:25:37 => POST || command POST => URL: https://api.twitch.tv/kraken/oauth2/token
05-21-16||05:25:37 => POST || POST option: client_id=>asd (these are correct)
05-21-16||05:25:37 => POST || POST option: client_secret=>asd (these are correct)
05-21-16||05:25:37 => POST || POST option: grant_type=>authorization_code
05-21-16||05:25:37 => POST || POST option: redirect_uri=>http://localhost/(not important)/
05-21-16||05:25:37 => POST || POST option: code=>(the code returned by twitch)
05-21-16||05:25:38 => POST || Status Returned: 403
05-21-16||05:25:38 => POST || Cleaning memory
05-21-16||05:25:38 => POST || Returning result
05-21-16||05:25:38 => Generate_Token || Access token not returned
05-21-16||05:25:38 => Generate_Token || Cleaning memory
05-21-16||05:25:38 => Request_Auth || Generating redirect URL
05-21-16||05:25:38 => Request_Auth || Cleaning memory

Above is the logged message when trying to obtain the token.

```
{
	"token": false,
	"grants": []
}
```

**Comment by IBurn36360** [comment]
Is this being test purely on a localhost environment, if not...

`05-21-16||05:25:37 => POST || POST option: redirect_uri=>http://localhost/(not important)/`

The above line is your entire problem.  Your redirect URI **MUST** match your actual authorization landing page.  I'm looking back over the Twitch API docs in case there is something else at work here, or if something has changed since the last time I looked at the API (It may or may not have been quite a while since I have done anything with the API on a PHP level)

**Comment by Sydth** [comment]
The URI matches the one I have for Twitch.

`http://localhost/peacebot/?code=OAUTHCODE&scope=user_read+channel_editor+channel_commercial+user_follows_edit+channel_feed_read`

Is what is received.

**Comment by Sydth** [comment]
I didn't mean to close this.

**Comment by IBurn36360** [comment]
All good, Do you have some time to hop onto my TeamSpeak server?  I may be able to assist you better with faster communication.  If you do not want to hop onto my server, I am willing to use an alternate form of communication (I'll post a roundup once we get the cause of the problem)

**Comment by Sydth** [comment]
Sure.

**Comment by IBurn36360** [comment]
The teamspeak information is:

Host: areqgaming.com
Password: AReq

Let me know when you have it and I'll pull this message so it isn't in public domain for long

**Comment by IBurn36360** [comment]
This ended up being a PHP7 compatibility issue.  Reverting to production PHP versions (5.0-5.7) resolved the issue.  A future version will be made PHP7 compatible.
